language: node_js
node_js:
  - "6"

git:
  depth: 10

before_script:
    - npm rebuild
script:
    - yarn generate
after_success:
    - openssl aes-256-cbc -K $encrypted_7cf8ca89b90b_key -iv $encrypted_7cf8ca89b90b_iv -in coding-deploy-key.enc -out ../coding-deploy-key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ../coding-deploy-key
    - ssh-add ../coding-deploy-key
    - ls -al
    - git config --global user.email "twang2218@gmail.com"
    - git config --global user.name "Tao Wang"
    - yarn deploy
    - rm ../coding-deploy-key
