sudo: required
language: node_js
node_js:
  - "8"

services:
  - docker

git:
  depth: 10

before_script:
    - npm rebuild
script:
    - yarn generate
after_success:
# Get ssh key
    - echo -e "Host git.coding.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - openssl aes-256-cbc -K $encrypted_7cf8ca89b90b_key -iv $encrypted_7cf8ca89b90b_iv -in coding-deploy-key.enc -out ../coding-deploy-key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ../coding-deploy-key
    - ssh-add ../coding-deploy-key
# Sync to coding.net
    - git remote add coding git@git.coding.net:twang2218/twang2218.git
    - git push coding master
# Deploy the pages
    - du -sh *
    - yarn deploy
    - rm ../coding-deploy-key
# Build Docker image
    - docker build -t twang2218/blog.lab99.org .
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - export TAG=$(date +%Y-%m-%d)
    - docker tag twang2218/blog.lab99.org "twang2218/blog.lab99.org:$TAG"
    - docker push twang2218/blog.lab99.org
    - docker push "twang2218/blog.lab99.org:$TAG"
